### ISSUE TITLE
crash with atio6axxx.dll

### ISSUE THREAD

**Issue by tyukara** [grondag/canvas#70] opened 2020-08-04 15:45 UTC
Hello. I have tried your canvas-mc116-1.0.871.jar in my multimc environment.
After starting minecraft, I was able to open the canvas settings screen from the title screen and from the settings.
However, after selecting the world and the map loads to 100%, it crashes after the "Connecting to server" message.
The log for that is as follows

https://paste.ee/p/4UwcI ...
https://paste.ee/p/ty75M

I'm using an i7-4790K CPU, 32GB of memory and an RX5700XT video card.
The AMD driver is the latest and I'm using 20.7.2.

The atio6axxx.dll shown in the log appears to be part of AMD's OpenGL driver.
So I am wondering if there is a conflict with ATI's video card.

**Comment by grondag** [comment] 2020-08-05 03:14
Thank you for the issue report.

From the logs it looks like the ATI drivers don't like something in the bloom shaders / frame buffer configuration.  Could you please turn off bloom in the Canvas configuration and see if it runs without crashing then or if It crashes in a different place?

If it crashes only when bloom is enabled that may help isolate the problem.

**Comment by tyukara** [comment] 2020-08-05 10:43
Thank you for your reply.
I immediately tried turning off Bloom and it ran fine.
I then tried turning on Bloom in the game and it was fine.
However, when I quit the game and ran it again, it crashed again.
Please let me know if there's anything else you'd like me to check.

I'm looking forward to the future of canvas.

**Comment by grondag** [comment] 2020-08-05 14:15
Interesting!  Will have a look soon to see if anything in that part of the code looks like it might be the cause.

**Comment by chaosophy** [comment] 2020-09-10 11:09
Does it also crash the same way when you go through portals to another dimension?
If so try AMD driver version 20.4.2

I mention this as there is an issue with OF + shaders and newer AMD drivers, so wondering if the same issue is affecting Canvas?

**Comment by grondag** [comment] 2020-12-14 20:57
If you have this issue, please try [build 1237](https://github.com/grondag/canvas/releases/download/1.0.1237-unstable/canvas-mc116-1.0.1237.jar) or later and report back.

**Comment by tyukara** [comment] 2020-12-14 23:59
I have confirmed that no error occurs with MC1.16.4 + canvas build1237 + radeon 20.12.1.
Thanks a lot!

Should I close this issue?

**Comment by grondag** [comment] 2020-12-15 00:16
Awesome!  Got several reports of this so let's get another confirmation or two if we can before closing.

Thanks.

**Comment by Motschen** [comment] 2020-12-15 09:37
I've also encountered this issue several times since I updated to the latest AMD drivers, but in the latest canvas version it works just fine.

**Comment by grondag** [comment] 2020-12-15 15:41
Thank you for the confirmations and extra thanks to @fewizz for isolating the problem and proposing a fix.

**Closed as completed by grondag** 2020-12-15 15:41 UTC
Labels: bug

**Comment by ghost** [comment] 2020-12-29 18:42
This might help - set the LOD to 2-4 (the game crashes at 0-1)
