### ISSUE TITLE
*Crash* and *Ton of errors*

### ISSUE THREAD

**Issue by UltraBlackLinux** [grondag/canvas#157] opened 2020-12-11 20:38 UTC
*Bigass crash here*
```
[21:36:54] [main/FATAL]: Reported exception thrown!
net.minecraft.class_148: Rendering entity in world
	at net.minecraft.class_898.method_3954(class_898.java:292) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.class_761.method_22977(class_761.java:1459) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.class_761.canvas_renderEntity(class_761.java:4837) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at grondag.canvas.render.CanvasWorldRenderer.renderWorld(CanvasWorldRenderer.java:543) ~[canvas-mc116-1.0.1202.jar:?]
	at grondag.canvas.render.CanvasWorldRenderer.method_22710(CanvasWorldRenderer.java:1135) ~[canvas-mc116-1.0.1202.jar:?]
	at net.minecraft.class_757.method_3188(class_757.java:727) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:546) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1048) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:681) [intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:215) [intermediary-minecraft-1.16.4-client.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_265]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_265]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_265]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_265]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224) [fabric-loader-0.10.8.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141) [fabric-loader-0.10.8.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27) [fabric-loader-0.10.8.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_265]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_265]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_265]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_265]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1024
	at grondag.canvas.material.property.MaterialTextureState.fromId(MaterialTextureState.java:186) ~[canvas-mc116-1.0.1202.jar:?]
	at grondag.canvas.material.state.AbstractStateFinder.texture(AbstractStateFinder.java:49) ~[canvas-mc116-1.0.1202.jar:?]
	at grondag.canvas.material.state.RenderLayerHelper.copyFromLayer(RenderLayerHelper.java:99) ~[canvas-mc116-1.0.1202.jar:?]
	at grondag.canvas.material.state.RenderLayerHelper.copyFromLayer(RenderLayerHelper.java:145) ~[canvas-mc116-1.0.1202.jar:?]
	at net.minecraft.class_1921$class_4687.canvas_materialState(class_1921.java:997) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at grondag.canvas.buffer.encoding.CanvasImmediate.getBuffer(CanvasImmediate.java:52) ~[canvas-mc116-1.0.1202.jar:?]
	at net.minecraft.class_922.method_4054(class_922.java:132) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.class_1007.method_4215(class_1007.java:65) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.class_1007.method_3936(class_1007.java:42) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.class_898.method_3954(class_898.java:261) ~[intermediary-minecraft-1.16.4-client.jar:?]
	... 24 more
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 12/11/20 9:36 PM
Description: Rendering entity in world

java.lang.ArrayIndexOutOfBoundsException: 1024
	at grondag.canvas.material.property.MaterialTextureState.fromId(MaterialTextureState.java:186)
	at grondag.canvas.material.state.AbstractStateFinder.texture(AbstractStateFinder.java:49)
	at grondag.canvas.material.state.RenderLayerHelper.copyFromLayer(RenderLayerHelper.java:99)
	at grondag.canvas.material.state.RenderLayerHelper.copyFromLayer(RenderLayerHelper.java:145)
	at net.minecraft.class_1921$class_4687.canvas_materialState(class_1921.java:997)
	at grondag.canvas.buffer.encoding.CanvasImmediate.getBuffer(CanvasImmediate.java:52)
	at net.minecraft.class_922.method_4054(class_922.java:132)
	at net.minecraft.class_1007.method_4215(class_1007.java:65)
	at net.minecraft.class_1007.method_3936(class_1007.java:42)
	at net.minecraft.class_898.method_3954(class_898.java:261)
	at net.minecraft.class_761.method_22977(class_761.java:1459)
	at net.minecraft.class_761.canvas_renderEntity(class_761.java:4837)
	at grondag.canvas.render.CanvasWorldRenderer.renderWorld(CanvasWorldRenderer.java:543)
	at grondag.canvas.render.CanvasWorldRenderer.method_22710(CanvasWorldRenderer.java:1135)
	at net.minecraft.class_757.method_3188(class_757.java:727)
	at net.minecraft.class_757.method_3192(class_757.java:546)
	at net.minecraft.class_310.method_1523(class_310.java:1048)
	at net.minecraft.class_310.method_1514(class_310.java:681)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at grondag.canvas.material.property.MaterialTextureState.fromId(MaterialTextureState.java:186)
	at grondag.canvas.material.state.AbstractStateFinder.texture(AbstractStateFinder.java:49)
	at grondag.canvas.material.state.RenderLayerHelper.copyFromLayer(RenderLayerHelper.java:99)
	at grondag.canvas.material.state.RenderLayerHelper.copyFromLayer(RenderLayerHelper.java:145)
	at net.minecraft.class_1921$class_4687.canvas_materialState(class_1921.java:997)
	at grondag.canvas.buffer.encoding.CanvasImmediate.getBuffer(CanvasImmediate.java:52)
	at net.minecraft.class_922.method_4054(class_922.java:132)
	at net.minecraft.class_1007.method_4215(class_1007.java:65)
	at net.minecraft.class_1007.method_3936(class_1007.java:42)

-- Entity being rendered --
Details:
	Entity Type: minecraft:player (net.minecraft.class_745)
	Entity ID: 55
	Entity Name: Auhp
	Entity's Exact location: -40.50, 65.00, 22.50
	Entity's Block location: World: (-41,65,22), Chunk: (at 7,4,6 in -3,1; contains blocks -48,0,16 to -33,255,31), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null

-- Renderer details --
Details:
	Assigned renderer: net.minecraft.class_1007@69789e0d
	Location: -72.00,-1.77,-9.00 - World: (-72,-2,-9), Chunk: (at 8,-1,7 in -5,-1; contains blocks -80,0,-16 to -65,255,-1), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Rotation: -97.03125
	Delta: 0.339566
Stacktrace:
	at net.minecraft.class_898.method_3954(class_898.java:261)
	at net.minecraft.class_761.method_22977(class_761.java:1459)
	at net.minecraft.class_761.canvas_renderEntity(class_761.java:4837)
	at grondag.canvas.render.CanvasWorldRenderer.renderWorld(CanvasWorldRenderer.java:543)
	at grondag.canvas.render.CanvasWorldRenderer.method_22710(CanvasWorldRenderer.java:1135)
	at net.minecraft.class_757.method_3188(class_757.java:727)

-- Affected level --
Details:
	All players: 13 total; [class_746['UltraBlack_'/829859, l='ClientLevel', x=31.50, y=65.00, z=31.50], class_745['Czepusss'/54, l='ClientLevel', x=41.72, y=65.00, z=22.34], class_745['ratolideos'/56, l='ClientLevel', x=22.50, y=65.00, z=41.50], class_745['BingBingBongBin'/41, l='ClientLevel', x=-21.50, y=65.00, z=41.50], class_745['Habibe_XD'/94, l='ClientLevel', x=-30.50, y=65.00, z=31.50], class_745['AlantheAstronaut'/52, l='ClientLevel', x=-30.72, y=65.00, z=-30.72], class_745['_ItzMarCoo_'/48, l='ClientLevel', x=31.50, y=65.00, z=-30.50], class_745['assa55in44'/50, l='ClientLevel', x=41.50, y=65.00, z=-21.50], class_745['mostdefharam'/126, l='ClientLevel', x=31.50, y=78.06, z=31.50], class_745['Auhp'/55, l='ClientLevel', x=-40.50, y=65.00, z=22.50], class_745['moh1_1'/93, l='ClientLevel', x=-40.50, y=65.00, z=-21.50], class_745['ZaGameboy'/51, l='ClientLevel', x=-21.37, y=65.00, z=-40.67], class_745['XtremeThunder'/46, l='ClientLevel', x=22.50, y=65.00, z=-40.50]]
	Chunk stats: Client Chunk Cache: 5041, 125
	Level dimension: minecraft:overworld
	Level spawn location: World: (-71,4,67), Chunk: (at 9,0,3 in -5,4; contains blocks -80,0,64 to -65,255,79), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 36971237 game time, 1 day time
	Server brand: vanilla
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:449)
	at net.minecraft.class_310.method_1587(class_310.java:2239)
	at net.minecraft.class_310.method_1514(class_310.java:699)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
```

*And here the other errors*
```
[22:01:57] [main/FATAL]: Error executing task on Client
java.lang.IllegalStateException: Invalid entity data item type for field 19 on entity class_1493['Wolf'/626171, l='ClientLevel', x=9.50, y=159.00, z=31.50]: old=14(class java.lang.Integer), new=false(class java.lang.Boolean)
	at net.minecraft.class_2945.method_12785(class_2945.java:241) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.class_2945.method_12779(class_2945.java:228) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.class_634.method_11093(class_634.java:568) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.class_2739.method_11808(class_2739.java:42) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.class_2739.method_11054(class_2739.java:11) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:144) [intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:118) [intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:103) [intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1015) [intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:681) [intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:215) [intermediary-minecraft-1.16.4-client.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_265]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_265]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_265]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_265]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224) [fabric-loader-0.10.8.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141) [fabric-loader-0.10.8.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27) [fabric-loader-0.10.8.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_265]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_265]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_265]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_265]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
```

**Comment by grondag** [comment] 2020-12-12 05:24
Please include the entire log.  There are many different versions of Canvas in the wild with big variations in the code and they all can be affected by their runtime environment.

**Comment by UltraBlackLinux** [comment] 2020-12-12 08:16
@grondag https://paste.ee/p/ztGLr
this is the log when I start up minecraft, I don't have the old crashlog anymore


(Oh, I see, the canvas log)
```

[09:15:32] [main/INFO]: ==================  CANVAS RENDERER DEBUG INFORMATION ==================
[09:15:32] [main/INFO]:  Java: 1.8.0_265 64bit
[09:15:32] [main/INFO]:  CPU: 12x AMD Ryzen 5 2600X Six-Core Processor
[09:15:32] [main/INFO]:  GPU: Using framebuffer using OpenGL 3.0  3.2.2 build 10
[09:15:32] [main/INFO]:  OpenGL: Radeon RX 560 Series (POLARIS11, DRM 3.39.0, 5.9.11-3-MANJARO, LLVM 11.0.0) GL version 4.6 (Compatibility Profile) Mesa 20.2.3, X.Org
[09:15:32] [main/INFO]:  VboArb: N  VaoEnabled: Y  VaoArb: N
[09:15:32] [main/INFO]:  (This message can be disabled by configuring logMachineInfo = false.)
[09:15:32] [main/INFO]: ========================================================================
```
canvas-mc116-1.0.1202



EDIT: Fresh crash: https://paste.ee/p/O0aCP
(Updated to look, if the crash still persists)

**Comment by grondag** [comment] 2020-12-12 21:43
This should be fixed in build [1230](https://github.com/grondag/canvas/releases/download/1.0.1230-unstable/canvas-mc116-1.0.1230.jar) or at least much better.

The problem is your game had loaded more than 1024 unique textures, which is more than I expected.  But if you have mods that add many custom entities or play on a server with lots of unique player skins then I suppose it can happen.

The limit has been increased to 4096 and a check added that prevents a crash and adds a much more helpful message if it happens again.

Thank you for the logs.

**Closed as completed by grondag** 2020-12-12 21:43 UTC
Labels: question, cannot reproduce

**Comment by UltraBlackLinux** [comment] 2020-12-12 22:22
@grondag the error shown at the very bottom is still spamming my logs - it's for potions, cats, horses, ... all those entity stuffs - is there something you can do about this?

**Comment by grondag** [comment] 2020-12-13 01:07
If you mean `java.lang.IllegalStateException: Invalid entity data item type...` I don't see anything to suggest Canvas is causing it.

**Comment by UltraBlackLinux** [comment] 2020-12-18 14:35
@grondag does this have something to do with canvas https://paste.ee/p/SFrtA
My whole client lags af when there are many particles and stuff, e.g. Hypixel skyblock catacombs
Edit: Hmm seems like not, might be the same error as described above :/
