### ISSUE TITLE
Item entities with glowing effect invisible

### ISSUE THREAD

**Issue by UltraBlackLinux** [grondag/canvas#183] opened 2021-01-01 19:19 UTC
Hey, there,
I have 2 topics with me:
1. On Hypixel skyblock, all dropped items get the glowing effect, but canvas renderer, makes them invisible, here a side-to-side comparison with and without canvas, to show my problem:
![Screenshot_20210101_201209](https://user-images.githubusercontent.com/62404294/103444935-430d7100-4c6e-11eb-8449-df45ab6d0acf.png)

2. Please make a support discord, where you can quickly ask for help, without having to create an issue, it would really help (me) out!

Thanks!

**Comment by grondag** [comment] 2021-01-01 19:51
Thank you for the issue report.

There is already a discord for my mods: https://discord.gg/7NaqR2e.  I've added a link to the read me.

**Comment by spiralhalo** [comment] 2022-01-13 14:18
This should be fixed by https://github.com/vram-guild/canvas/commit/3cd5d5e8a3e5ccf05ea61c2bb528483863da0502 - https://github.com/vram-guild/canvas/commit/0c0c275d11b5372dcf82f3e166036b6fd27c3be5

But grondag hasn't reviewed the code yet. Will close if the changes stay by the next release.

**Comment by supsm** [comment] 2022-10-13 21:46
cannot reproduce in latest canvas, looks like the fix was kept @spiralhalo

**Closed as completed** 2022-10-14 01:07 UTC
Labels: bug, compatibility
