### ISSUE TITLE
Crashes upon loading a world. (1.16.5)

### ISSUE THREAD

**Issue by ShadoUrufu** [grondag/canvas#272] opened 2021-06-09 02:19 UTC
The game crashes, primarily upon trying to load amplified world, from what I noticed. I really enjoy amplified worlds, and my best map is on one. 

But yeah, I don't really know what causes it. even made a new world today for testing, it loaded, partially, and then crashed, i think when i started moving to trying to get to the menu to adjust some settings. 

Edit: NVM, After I finished writing this message and went back to the game to test some settings, it crashed. I guess amplified just makes it crash faster. 

I have mods loaded in, but i also tried without any mods and got the same result. 

[Crash Loh.txt](https://github.com/grondag/canvas/files/6620662/Crash.Loh.txt)

**Comment by spiralhalo** [comment] 2021-06-09 03:39
Possible duplicate of #234

Use latest fabric api.

**Closed as completed** 2021-06-27 15:35 UTC
Labels: duplicate
