### ISSUE TITLE
Chunk rendering sporadic, world holes everywhere, XRay Hacks possible

### ISSUE THREAD

**Issue by Sollace** [grondag/canvas#204] opened 2021-02-10 09:06 UTC
Version: Canvas-mc116-1.0.1267
Mc: 1.16.4 (dev environment)
Fabric: 0.30.0+1.16
Loader: 0.10.6+build.214
No other mods are included that mess with rendering

After using Canvas for just a few moments I immediately notices a major issue: Chunks weren't rendering consistently and large parts of the world are not visible at all. It seems to be only rendering a narrow column of where the player is looking with no possibility to turn it off (I turned off all the options and it still happens)

The problem becomes especially noticable in third person and when flying and looking in the distance. Sometimes even chunks that are right on top of you turn invisible.

![](https://media.discordapp.net/attachments/507982478276034570/808980268315574272/unknown.png)
![](https://media.discordapp.net/attachments/507982478276034570/808980683845795840/unknown.png)

On top of that I can use this to X-Ray! If you position the camera at the right angle you can see other caves right through the ground and walls.
![](https://media.discordapp.net/attachments/507982478276034570/808982453444280330/unknown.png?width=994&height=559)
![image](https://user-images.githubusercontent.com/6429283/107487306-bae48a80-6b8e-11eb-9162-4dffc2baee4a.png)

**Comment by grondag** [comment] 2021-02-15 15:10
Unable to reproduce with the information provided.  "No other mods are included that mess with rendering" is not the same as no other mods.

**Comment by grondag** [comment] 2021-02-26 14:55
Closing absent more info.  Please reopen if/when steps to reproduce are known.

**Closed as completed by grondag** 2021-02-26 14:55 UTC
Labels: question, cannot reproduce
