### ISSUE TITLE
JVM Crash (OpenJDK, EXCEPTION_ACCESS_VIOLATION)

### ISSUE THREAD

**Issue by Shyrogan** [grondag/canvas#159] opened 2020-12-11 23:17 UTC
Often when loading into a world, the client crashes. I feel like this is due to the usage of OpenJDK with Canvas.

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffaec2cc052, pid=8012, tid=0x0000000000001e24
#
# JRE version: OpenJDK Runtime Environment (8.0_275-b01) (build 1.8.0_275-b01)
# Java VM: OpenJDK 64-Bit Server VM (25.275-b01 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# C  [atio6axx.dll+0xbbc052]
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# If you would like to submit a bug report, please visit:
#   https://github.com/AdoptOpenJDK/openjdk-support/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

---------------  T H R E A D  ---------------

Current thread (0x00000217c5d80800):  JavaThread "Render thread" [_thread_in_native, id=7716, stack(0x000000e52b800000,0x000000e52b900000)]

siginfo: ExceptionCode=0xc0000005, reading address 0x00000217f9c32000

Registers:
RAX=0x0000000000001fff, RBX=0x00000217f9c30000, RCX=0xffffffffffffffff, RDX=0x00000000034304b0
RSP=0x000000e52b8fd2f0, RBP=0x000000e52b8fd3f0, RSI=0x0000000000000000, RDI=0x0000000000000000
R8 =0x0000000000000343, R9 =0x0000000000000040, R10=0x0000000000000340, R11=0x0400000000800000
R12=0x0000000000000000, R13=0x0000000000000000, R14=0x0000000000000000, R15=0x0000000000000000
RIP=0x00007ffaec2cc052, EFLAGS=0x0000000000010206

Top of Stack: (sp=0x000000e52b8fd2f0)
0x000000e52b8fd2f0:   00000217c5d20000 00000217c5d20000
0x000000e52b8fd300:   00000217e646f250 000000000000007e
0x000000e52b8fd310:   000000000000007e 000000000000007e
0x000000e52b8fd320:   0000000000001550 0000000000001610
0x000000e52b8fd330:   00000000e8850101 00000217ead23b00
0x000000e52b8fd340:   0000000000000000 00007ffb00000000
0x000000e52b8fd350:   00000217e646f260 0000000002ec03c0
0x000000e52b8fd360:   0000000000000000 00000000000002ec
0x000000e52b8fd370:   00000000000001d3 0000000000000000
0x000000e52b8fd380:   0000000000000000 0000000000000000
0x000000e52b8fd390:   0000000000000000 0000000000000000
0x000000e52b8fd3a0:   0000000000000000 0000000000000000
0x000000e52b8fd3b0:   0000000000000000 0000000000000000
0x000000e52b8fd3c0:   000000000000007e 00000217c5c8c780
0x000000e52b8fd3d0:   00000217c5d33014 00000217e47d9e40
0x000000e52b8fd3e0:   0000000000000001 0000000000000010 

Instructions: (pc=0x00007ffaec2cc052)
0x00007ffaec2cc032:   e8 01 00 00 48 8b f7 48 89 7d b0 48 89 7d b8 48
0x00007ffaec2cc042:   89 7c 24 70 4a 8b 1c fb 48 85 db 74 4c 48 8b c1
0x00007ffaec2cc052:   80 7c 03 01 00 48 8d 40 01 75 f5 48 8d 78 01 48
0x00007ffaec2cc062:   89 7d b8 48 85 ff 74 1c 48 8d 77 0f 48 83 e6 f0 


Register to memory mapping:

RAX=0x0000000000001fff is an unknown value
RBX=0x00000217f9c30000 is an unknown value
RCX=0xffffffffffffffff is an unknown value
RDX=0x00000000034304b0 is an unknown value
RSP=0x000000e52b8fd2f0 is pointing into the stack for thread: 0x00000217c5d80800
RBP=0x000000e52b8fd3f0 is pointing into the stack for thread: 0x00000217c5d80800
RSI=0x0000000000000000 is an unknown value
RDI=0x0000000000000000 is an unknown value
R8 =0x0000000000000343 is an unknown value
R9 =0x0000000000000040 is an unknown value
R10=0x0000000000000340 is an unknown value
R11=0x0400000000800000 is an unknown value
R12=0x0000000000000000 is an unknown value
R13=0x0000000000000000 is an unknown value
R14=0x0000000000000000 is an unknown value
R15=0x0000000000000000 is an unknown value


Stack: [0x000000e52b800000,0x000000e52b900000],  sp=0x000000e52b8fd2f0,  free space=1012k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [atio6axx.dll+0xbbc052]
C  [atio6axx.dll+0xbb988f]
C  [atio6axx.dll+0xdcb467]
C  0x00000217c7764347

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  org.lwjgl.opengl.GL20C.nglShaderSource(IIJJ)V+0
j  org.lwjgl.opengl.GL20C.glShaderSource(ILjava/lang/CharSequence;)V+38
j  org.lwjgl.opengl.GL20.glShaderSource(ILjava/lang/CharSequence;)V+2
j  grondag.canvas.shader.GlShader.load()V+60
j  grondag.canvas.shader.GlShader.glId()I+8
j  grondag.canvas.shader.GlShader.attach(I)Z+1
j  grondag.canvas.shader.GlProgram.loadInner()Z+29
j  grondag.canvas.shader.GlProgram.load()V+40
j  grondag.canvas.shader.ProcessShader.activate()Lgrondag/canvas/shader/ProcessShader;+216
j  grondag.canvas.render.CanvasFrameBufferHacks.applyBloom()V+476
j  net.minecraft.client.render.GameRenderer.handler$zjf000$afterRenderHand(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V+6
j  net.minecraft.client.render.GameRenderer.renderHand(Lnet/minecraft/client/util/math/MatrixStack;Lnet/minecraft/client/render/Camera;F)V+291
j  net.minecraft.client.render.GameRenderer.renderWorld(FJLnet/minecraft/client/util/math/MatrixStack;)V+555
J 13138 C1 net.minecraft.client.render.GameRenderer.render(FJZ)V (882 bytes) @ 0x00000217c9a7d07c [0x00000217c9a7b6e0+0x199c]
J 12941 C1 net.minecraft.client.MinecraftClient.render(Z)V (950 bytes) @ 0x00000217c9488c7c [0x00000217c9484940+0x433c]
j  net.minecraft.client.MinecraftClient.run()V+83
j  net.minecraft.client.main.Main.main([Ljava/lang/String;)V+1379
v  ~StubRoutines::call_stub
j  sun.reflect.NativeMethodAccessorImpl.invoke0(Ljava/lang/reflect/Method;Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;+0
j  sun.reflect.NativeMethodAccessorImpl.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;+100
J 3634 C1 sun.reflect.DelegatingMethodAccessorImpl.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object; (10 bytes) @ 0x00000217c8531d6c [0x00000217c8531c40+0x12c]
J 3637 C1 java.lang.reflect.Method.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object; (62 bytes) @ 0x00000217c85327e4 [0x00000217c85323c0+0x424]
j  net.fabricmc.loader.game.MinecraftGameProvider.launch(Ljava/lang/ClassLoader;)V+71
j  net.fabricmc.loader.launch.knot.Knot.init([Ljava/lang/String;)V+689
j  net.fabricmc.loader.launch.knot.KnotClient.main([Ljava/lang/String;)V+33
j  java.lang.invoke.LambdaForm$DMH.invokeStatic_L_V(Ljava/lang/Object;Ljava/lang/Object;)V+10
j  java.lang.invoke.LambdaForm$MH.invokeExact_MT(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)V+16
j  net.fabricmc.devlaunchinjector.Main.main([Ljava/lang/String;)V+307
v  ~StubRoutines::call_stub

```

**Comment by Kichura** [comment] 2020-12-12 14:57
Have you tried running canvas on AdoptOpenJDK 11 with HotSpot to see if this problem goes away?

**Comment by grondag** [comment] 2020-12-12 20:55
Appears to be a duplicate of #70.  Disabling bloom may be a (not great) workaround until fixed.

**Closed as completed by grondag** 2020-12-12 20:55 UTC
Labels: bug, duplicate

**Comment by UltraBlackLinux** [comment] 2020-12-12 22:44
@Kichura minecraft is java 8, everything else can and will cause problems.

**Comment by Kichura** [comment] 2020-12-28 14:11
> @Kichura minecraft is java 8, everything else can and will cause problems.

I will likely have to doubt this one as java 11 has ran pretty smoothly on this unit unlike 7 & 8, Although in reality; This should be up to you to decide whether if you wanna update to atleast adoptopenjdk 11 or not.

And since this DLL is related to AMD, I also suggest updating your AMD drivers aswell to latest version possible.
