### ISSUE TITLE
Podzol/farmland/birch leaves are black

### ISSUE THREAD

**Issue by ArkQuark** [grondag/canvas#266] opened 2021-06-03 09:45 UTC
Minecraft: 1.17 pre4
Canvas: canvas-mc117-1.17-1.0.1578
Another mods: clothconfig 5.0.34, dynamicfps 2.0.2, entityculling 1.2.2-prerelease1, fabricapi 0.34.8, fabriczero 0.2.1, architectury 2.0.5, rei 6.0.224-alpha, wthit 3.5.1, smoothboot 1,6.0.
pipelines - basic canvas
ao shading - none
![image](https://user-images.githubusercontent.com/74979909/120624277-35e8ee00-c469-11eb-97e6-36d4aac4a6ca.png)

**Comment by ArkQuark** [comment] 2021-06-03 09:48
podzol fixed by smooth lightning to maximum/ but farmland are black

**Comment by ArkQuark** [comment] 2021-06-03 13:56
![image](https://user-images.githubusercontent.com/74979909/120656841-a2291900-c48c-11eb-9fbf-9f5002369189.png)

**Comment by LiSongMWO** [comment] 2021-06-05 22:37
Not sure if related but I had Oak turn black randomly until I restarted minecraft

**Comment by Iltotore** [comment] 2021-07-04 12:17
This bug happens with all solid blocks for me. I am using the latest Canvas 1.17 with the latest release of Fabric Loader and API.

This is a huge barrier to the adoption of Canvas because it prevents me to play the game normally.

**EDIT: This seems to only happen when disabling smooth lights, as said by @ArkQuark above.**

![2021-07-04_14 19 19](https://user-images.githubusercontent.com/42907886/124384716-e4838700-dcd2-11eb-8e3a-6ff694d3838d.png)

**Comment by spiralhalo** [comment] 2021-07-06 03:50
Smooth lighting OFF has been fixed (#235)

I haven't encountered this bug in a while. There has been a few changes to resource and material loading. Can someone confirm this bug in 1.17 and the latest github release of Canvas?

**Comment by supsm** [comment] 2023-02-27 18:32
closing as nobody has been able to reproduce

**Closed as not planned by supsm** 2023-02-27 18:32 UTC
Labels: question
