### ISSUE TITLE
Canvas crashes modpack.

### ISSUE THREAD

**Issue by toErIpNid** [grondag/canvas#245] opened 2021-05-05 00:40 UTC
[crash-2021-05-04_19.39.05-client.txt](https://github.com/grondag/canvas/files/6424569/crash-2021-05-04_19.39.05-client.txt)
 All versions are latest except for minecraft, which is 1.16.5

**Comment by heymanMC** [comment] 2021-05-05 00:42
downgrade your fabric api version to 0.32.5

**Comment by toErIpNid** [comment] 2021-05-08 01:09
Made a new modpack, tried canvas before and after downgrading the api with no success. 

Latest crash log: 
[crash-2021-05-07_20.07.52-client.txt](https://github.com/grondag/canvas/files/6444901/crash-2021-05-07_20.07.52-client.txt)

**Comment by IMS212** [comment] 2021-05-08 01:27
API is not downgraded to **0.32.5** in that log?

**Comment by grondag** [comment] 2021-05-22 18:09
Duplicate of #234

**Closed as completed by grondag** 2021-05-22 18:09 UTC
