### ISSUE TITLE
Crash after load world

### ISSUE THREAD

**Issue by Dlanis** [grondag/canvas#234] opened 2021-04-15 10:07 UTC
[crash-2021-04-15_15.57.12-client.txt](https://github.com/grondag/canvas/files/6317012/crash-2021-04-15_15.57.12-client.txt)

**Comment by fewizz** [comment] 2021-04-15 13:09
Should work with previous version of Fabric API. (because of [this](https://github.com/FabricMC/fabric/commit/6d5e24549f1c6faa51b432ca03a507d6b30719ab#diff-573329092a3a8338cdb31df56a8c7488ae7a9b53e21a8aa77a125422869be2bbL100) commit prob)

**Comment by pionearly** [comment] 2021-04-22 08:12
Getting a crash on load as well,
[Crashlog with NEC](https://gist.githubusercontent.com/natanfudge/dc8481ee6f28f181da7816ddc4f4c027/raw/82d64fb0acd1a7ae2f974e4c4addebd41ce2d815/crash.txt)
Will try a downgrade of the modpack if the issue is unlikely to be fixed on canvas' end anytime soon

**Comment by spiralhalo** [comment] 2021-04-22 08:23
Downgrade Fabric API to 0.32.5.

A lot of people are getting this crash. I don't know if Grondag plans to fix it as he's stopped developing on 1.16.

**Comment by pionearly** [comment] 2021-04-22 09:07
I see, that’s a shame but thanks for the quick reply.

**Comment by grondag** [comment] 2021-05-22 18:09
Will be fixed in next release.

**Closed as completed by grondag** 2021-05-22 18:09 UTC
Labels: bug
