### ISSUE TITLE
crashes when i join a server with colormatic alongside canvas

### ISSUE THREAD

**Issue by arceuss** [grondag/canvas#127] opened 2020-11-11 16:25 UTC
[https://paste.ee/p/TVpjO](https://paste.ee/p/TVpjO) log here

**Comment by spiralhalo** [comment] 2020-12-14 20:01
Ah, seems that the log expired.

I can't reproduce this crash in either multiplayer server (vanilla, papermc) and single player world. Using Canvas 1.0.1236 and Colormatic 2.2.7+mc.1.16.3. Using Jicklus resource pack (seems to support OF colors).

What version of Canvas are you using? Does it only crash with a specific resource pack?

**Comment by spiralhalo** [comment] 2021-06-27 18:48
Gonna close it until it can be confirmed reproducible.

**Closed as completed by spiralhalo** 2021-06-27 18:48 UTC
