### ISSUE TITLE
The world has no light whatsoever when Canvas is Installed.

### ISSUE THREAD

**Issue by doctor-something5000** [grondag/canvas#196] opened 2021-01-18 01:48 UTC
The world when loaded has no light at all when Canvas is installed. However, without Canvas, the lighting is fine.
[Screenshot](https://imgur.com/a/OxPxlYn)

**Comment by ramidzkh** [comment] 2021-01-27 05:36
What shaderpack(s) and mods?

**Comment by Reeses-Puffs** [comment] 2021-01-27 14:11
yeah, you need to provide much more information than just "it looks black"

**Comment by doctor-something5000** [comment] 2021-01-28 03:59
I have the following mods

**Comment by doctor-something5000** [comment] 2021-01-28 03:59
https://drive.google.com/file/d/1lt0M5ECMQdSe0Q8I3GPfq-PkgxrfCyAh/view?usp=sharing

**Comment by spiralhalo** [comment] 2021-06-27 17:01
That is a rar file. You should get a mod list from the logs. And bugs should be reproducible with only Canvas unless it's clearly marked as incompatibility with a specific mod.

Also, the issue is unclear from just that image. Can you confirm if this is related to #264 ?

**Closed as completed** 2021-07-04 09:35 UTC
Labels: question
