### ISSUE TITLE
The second I move my mouse (or the in-game camera) my game crashes. Not sure if it has to do with me having an AMD R9 Fury Graphics card.

### ISSUE THREAD

**Issue by TheGartmans522** [grondag/canvas#251] opened 2021-05-14 17:50 UTC

**Comment by spiralhalo** [comment] 2021-05-14 19:23
I suspect it has something to do with the block outline drawing bug (since it only triggers when you're pointing at a block)

Check your crash report if it says "drawBlockOutline" somewhere in the stack trace.

If that is the case, downgrade to Fabric api 0.32.5. A fix is being worked on but won't come out until at least this weekend.

**Comment by HumbleDeer** [comment] 2021-05-21 06:54
I also have this issue currently; The crash log provided by NotEnoughCrashes is pasted here for possible use: 
https://gist.githubusercontent.com/natanfudge/f15f55802e85bcff52189256c854a01e/raw/d10d108ce6b4394cd33d140d4c25ecb3e1a64e32/crash.txt

**Comment by irb** [comment] 2021-05-25 22:19
This occurs for me too now, running fabric-api-0.32.5+1.16 with canvas-mc116-1.0.1511.

This doesn't occur with fabric-api-0.32.5+1.16 / canvas-mc116-1.0.1267.

java.lang.NoSuchMethodError: 'void net.fabricmc.fabric.impl.client.rendering.WorldRenderContextImpl.**prepareBlockOutline**(net.minecraft.class_1297, double, double, double, net.minecraft.class_2338, net.minecraft.class_2680)'

However, running fabric-api-0.34.6+1.16 with canvas 1.0.1511 seems to load up fine.

**Comment by spiralhalo** [comment] 2021-05-26 04:06
1.0.1511 is *the* fix. Now you need to *upgrade* your fabric api to 0.34.2. 0.32.5 and below is no longer compatible.

**Comment by TheGartmans522** [comment] 2021-05-26 04:08
Thanks for the update!

**Comment by spiralhalo** [comment] 2021-06-27 15:37
If no further information is provided, I'm gonna assume this is duplicate of #234

**Closed as completed** 2021-06-27 15:37 UTC
Labels: duplicate
