### ISSUE TITLE
Crash with Campanion rope bridges

### ISSUE THREAD

**Issue by florensie** [grondag/canvas#128] opened 2020-11-11 20:51 UTC
https://pastebin.com/iq9GGk9K

**Comment by aniMattor** [comment] 2020-12-11 08:23
I had this issue, too. It seems to be related to the "ghosted" preview that renders when placing bridges. when placing a bridge the world crashes, and cannot be reopened, unless I disable canvas. Then it will open a gain normally and if I cancel the bridge, it can run again with canvas enabled. I think the issue is the same with the preview for placing tents. I reported this on the Campanion page and was told the issue was with Canvas.

**Comment by grondag** [comment] 2020-12-13 16:59
This problem is on Campanion's side and can't be helped until they change something, unfortunately.  I've posted an issue there and offered to help.

~~A not great workaround seems to be switching to creative mode temporarily to place the bridge.~~

Build 1234 and later catch this error to prevent crashing.  The bridge will not render correctly until all the planks are added, but it can still be completed successfully.

**Comment by spiralhalo** [comment] 2020-12-14 21:20
From what I see, the workaround on Canvas side prevents crash but renders the bridge with the wrong texture.

Campanion got a recent commit wherein bridge can be built in survival without crash and it renders with the correct texture.

**Comment by grondag** [comment] 2020-12-14 21:24
> Campanion got a recent commit wherein bridge can be built in survival without crash and it renders with the correct texture.

Yeah my workaround was mostly to prevent the crash.  Looks like the Campanion team got right on this and should be fixed now.  Nice.

**Closed as completed by grondag** 2020-12-14 21:24 UTC
Labels: compatibility, back burner, depends on someone else
