### ISSUE TITLE
Issue w/astromine

### ISSUE THREAD

**Issue by by-moan** [grondag/canvas#59] opened 2020-07-18 17:36 UTC
There is an issue idk is fixed on recent versions of canvas when if you equip the astronaut helmet the game crashes and i cant enter the world unless i move the mod to other part and unequip the thing that crashes or i use an external tool to remove it of the inventory
canvas version is 1.0.784
astromine version is 1.2.1

**Comment by JanThomas118** [comment] 2020-07-20 21:16
I have tried this aswell: Canvas version: .823 Astromine: 1.2.3
I have equipped every helmet the mod has in the overworld and have not observed any crashes. 
What exactly did you do to make it crash?

**Comment by grondag** [comment] 2020-07-23 02:45
The 784 build is quite old and JanThomas188 was unable to reproduce. (Thank you for trying!)

Going to close this one. Please reopen with fresh details on how to reproduce if this is still happening.

**Closed as completed by grondag** 2020-07-23 02:45 UTC
Labels: cannot reproduce
