### ISSUE TITLE
Having bloom enabled causes crash on world load

### ISSUE THREAD

**Issue by UberApril** [grondag/canvas#124] opened 2020-11-05 00:41 UTC
I'm using an AMD GPU, there is no Crash log only normal logs as the game closes with Exit code 1
[latest.log](https://github.com/grondag/canvas/files/5491195/latest.log)

Whenever loading into a new dimension or world with bloom enabled the game crashes. If bloom is turned off it loads just fine.  However if i load into a world AND THEN Enable Bloom, the bloom works just fine with no issues or artifacts, It's only upon changing dimension or loading a world with bloom enabled that the game crashes.

**Comment by UberApril** [comment] 2020-11-05 21:08
[hs_err_pid17640.log](https://github.com/grondag/canvas/files/5497431/hs_err_pid17640.log)

Got a Log out of it. Happens without all my other mods installed too

**Comment by grondag** [comment] 2020-12-12 21:04
Appears to be a duplicate of #70

**Closed as completed by grondag** 2020-12-12 21:04 UTC
Labels: bug, duplicate
