### ISSUE TITLE
Error loading multiple resources

### ISSUE THREAD

**Issue by ghost** [grondag/canvas#163] opened 2020-12-12 12:50 UTC
A fatal error has been detected by the Java Runtime Environment:
EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ff982a4bad2, pid=9016, tid=0x000000000000241c
RE version: Java(TM) SE Runtime Environment (8.0_271-b09) (build 1.8.0_271-b09)
Java VM: Java HotSpot(TM) 64-Bit Server VM (25.271-b09 mixed mode windows-amd64 compressed oops)
Problematic frame:
C  [atio6axx.dll+0xbbbad2]
Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
An error report file with more information is saved as:
C:\Users\User\Desktop\MultiMC\instances\Fabric\.minecraft\hs_err_pid9016.log
If you would like to submit a bug report, please visit:
http://bugreport.java.com/bugreport/crash.jsp
The crash happened outside the Java Virtual Machine in native code.
See problematic frame for where to report the bug.
AL lib: (EE) alc_cleanup: 1 device not closed

**Comment by ghost** [comment] 2020-12-12 12:52
[hs_err_pid9016.log](https://github.com/grondag/canvas/files/5683093/hs_err_pid9016.log)

**Comment by grondag** [comment] 2020-12-12 20:56
Appears to be a duplicate of #70

**Closed as completed by grondag** 2020-12-12 20:56 UTC
Labels: bug, duplicate
