### ISSUE TITLE
Vanilla AO causes block rendered without lighting or gradient stripes when Smooth Lighting is OFF

### ISSUE THREAD

**Issue by ArkQuark** [grondag/canvas#264] opened 2021-06-01 21:35 UTC
Minecraft: 1.17 pre3
Canvas: canvas-mc117-1.17-1.0.1578
Another mods: clothconfig 5.0.34, cullleaves 2.1.0, dynamicfps 2.0.2, entityculling 1.2.2-prerelease1, fabricapi 0.34.8, fabriczero 0.2.1.
Screenshot:
![image](https://user-images.githubusercontent.com/74979909/120393332-6bdb8480-c33a-11eb-90aa-2a192877a0cd.png)

**Comment by Reeses-Puffs** [comment] 2021-06-01 21:44
It would be helpful if you posted your logs and your shader debug folder

**Comment by spiralhalo** [comment] 2021-06-02 03:04
Is your smooth lighting set to minimum?
Does it happen after changing pipelines, or immediately after loading a world?
Does restarting mc fix it?

If possible, please provide exact steps to reproduce it reliably.

**Comment by ArkQuark** [comment] 2021-06-02 08:49
Log:
https://pastebin.com/AZJcvwfW
shader debug folder is empty
smooth light = off
restart dont fix
its after loading world
[options.txt](https://github.com/grondag/canvas/files/6583160/options.txt)
i didn't touch options in canvas

**Comment by ArkQuark** [comment] 2021-06-02 09:01
i changed option ao shading to subtle_always but blocks are grey
![image](https://user-images.githubusercontent.com/74979909/120451498-2cdd1b80-c39a-11eb-91cd-e877c8ddbb3b.png)

**Comment by ArkQuark** [comment] 2021-06-02 09:02
if set ao shader to none this fixed

**Comment by spiralhalo** [comment] 2021-06-27 15:33
Can confirm this in 1.17 + more recent build.

Only happens when AO Shading is NORMAL and Smooth Lighting is OFF.

**Comment by Purpzie** [comment] 2021-06-27 23:53
Just ran into this issue as well. Turning on smooth lighting and then disabling it causes other weird effects:

![image](https://user-images.githubusercontent.com/25022704/123563180-dab0cf80-d778-11eb-94db-4ab0d943622c.png)

Additionally, while joining a world there were random black flashes in the sky (unable to reproduce again sadly). They didn't cover the whole sky, it was random areas. I had smooth lighting enabled (minimal). I'm not sure if that's related to this issue, but I'm mentioning it just in case.

**Comment by spiralhalo** [comment] 2021-07-06 00:05
Thank you for the additional reports. Both issues should be fixed now.

**Closed as completed** 2021-07-06 00:05 UTC
Labels: bug
